### PR TITLE
changes in HipoDataSync.

### PR DESCRIPTION
**Pull request by gavalian**
The back end of HipoDataSync is now tagged hipo writer. so events that are written will be arranged in buckets according to their tags.

### CODE REVIEW

**Comment by baltzell** [comment]
Probably this means recon-util will now preserve tags?

**Comment by gavalian** [comment]
Probably,
In theory yes, has to be tried


On Dec 9, 2020, at 4:06 PM, Nathan Baltzell <notifications@github.com<mailto:notifications@github.com>> wrote:



Probably this means recon-util will now preserve tags?

**Comment by raffaelladevita** [comment]
Can reading of tags be added too to clas-io?

**Comment by baltzell** [comment]
If I run a file through recon-util with this, then a `hipo-utils -dump -tags 1 -wait 1 `prints the following on every event:

`------- there are no more events -----
`

**Comment by gavalian** [comment]
What is this in regards to ? If you want to find out if tag=1 events are there, just do 
hips-utils -info filename.hipo

**Comment by baltzell** [comment]
This is a PR you submitted.

**Comment by gavalian** [comment]
Oh,yeah. Can you send me the resulting file when running through recon-utils ?

**Comment by baltzell** [comment]
You can run this through recon-util, it has non-zero tags in it:

/work/xrootd/hallb/clas12/backgroundfiles/rgb_spring2019/tor-1.00_sol-1.00/50nA_10200MeV/10k/00017.hipo

**Review by baltzell — APPROVED** [review]

**Pull request merged**
