### PR TITLE
TDC jitter correction for PCAL/EC

### PR DESCRIPTION
**Pull request by forcar**
* time-jitter (phase) correction
* fADC-TDC alignment constants and matching
* implement a3,a4 LEFF corrections to effective velocity

### CODE REVIEW

**Comment by baltzell** [comment]
Looks like `ECCommon`'s new `static triggerPhase` isn't thread-safe;  should instead be just a local in `initEC`.  And same for new `offset` table (although less dangerous since only run/ccdb-dependent).

(Also, nice to make `static` class variables `final` when appropriate, so easier to see what's going on:)

**Comment by raffaelladevita** [comment]
Dedicated entries for run range 0-100 for the new ccdb tables, time_jitter and fadc_offset, are needed for MC compatibility

**Comment by forcar** [comment]
Done.

**Comment by baltzell** [comment]
```
cd validation/advanced-tests
./run-eb-tests.sh electronproton
```

gives:


```
java.lang.ArithmeticException: / by zero
	at org.jlab.service.ec.ECCommon.readStripsHipo(ECCommon.java:135)
	at org.jlab.service.ec.ECCommon.initEC(ECCommon.java:80)
	at org.jlab.service.ec.ECEngine.processDataEvent(ECEngine.java:57)
	at org.jlab.clas.reco.EngineProcessor.processEvent(EngineProcessor.java:188)
	at org.jlab.clas.reco.EngineProcessor.processFile(EngineProcessor.java:219)
	at org.jlab.clas.reco.EngineProcessor.main(EngineProcessor.java:281)
```

**Comment by forcar** [comment]
Re-ran ./run-eb-tests.sh electronproton after bug fix.  Previous ArithmeticException / by zero does not occur.  However the test fails.  I do not have a clue why as all my private validation code works.


# Events = 998

Electrons Sectors:     0    0    0    0    0    0
Hadrons   Sectors:     0    0    4    0    0    0

2-Track Frac = 0.916

eEff         = 0.000
pEff         = NaN
piEff        = NaN
kEff         = NaN

gEff         = 0.000
nEff         = 0.000

epEff        = 0.000
epiEff       = 0.000
ekEff        = 0.000

misid        = NaN
missing      = NaN

#############################################################
E
Time: 0.737
There was 1 failure:
1) main(eb.EBTwoTrackTest)
java.lang.AssertionError: expected:<false> but was:<true>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)

**Comment by baltzell** [comment]
Check earlier in the log.  Probably there's an error printout before that.  I cloned your fork and the same test passed.

**Pull request merged**
