### PR TITLE
Add and fill software configuration bank

### PR DESCRIPTION
**Pull request by baltzell**
* Modify all poms to include version numbers in jar manifests
* Add JsonUtils convenience class for reading/writing/appending a JSON bank
* Add YAML filterer for recon-util to emulate the EngineData that services receive from CLARA
* Create/append COAT::config bank by all ReconstructionEngines
  * including service/coatjava versions and YAML contents
* Copy COAT::config to new tag-1 event in postprocessing

### CODE REVIEW

**Comment by baltzell** [comment]
Example of what COAT::config contains
Screen Shot 2020-11-24 at 2 13 34 PM

**Comment by gavalian** [comment]
This is a bank of string ? And where is this added ? Each event ?

On Nov 25, 2020, at 3:56 PM, Nathan Baltzell <notifications@github.com<mailto:notifications@github.com>> wrote:



Example of what COAT::config contains
[Screen Shot 2020-11-24 at 2 13 34 PM]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_6279258_100280757-2Dabae5300-2D2f36-2D11eb-2D92a2-2D28ce510bb849.png&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=HtDGjDqP3DcY85Ufwkq5sj_hCKw-SsuwwMhei0DIWyg&m=MJlyVVEXeJDUvGpHuV6K7VIOw-GsFLQi1gi5GZqquZI&s=idM9d-Z4G3NV944fBqhfz-ldydQ_pD68On6wWOykJcQ&e=>

**Comment by baltzell** [comment]
> This is a bank of string ? And where is this added ? Each event ?

Yes, it's a single variable byte array bank, like RAW::epics.

It's filled once per service.

**Comment by gavalian** [comment]
It’s good to know that our reconstruction services are already at version 1.0


On Nov 25, 2020, at 3:58 PM, Nathan Baltzell <notifications@github.com<mailto:notifications@github.com>> wrote:



This is a bank of string ? And where is this added ? Each event ?

Yes, it's a single variable byte array bank, like RAW::epics.

It's filled once per service.

**Comment by baltzell** [comment]
> It’s good to know that our reconstruction services are already at version 1.0

That comes from their pom.xmls

**Review by raffaelladevita — APPROVED** [review]

**Pull request merged**
