### PR TITLE
EB Update

### PR DESCRIPTION
**Pull request by josnewton**

### CODE REVIEW

**Comment by forcar** [comment]
Joseph,

1) Is there a reason you don’t initialize CalorimeterResponse(sector, layer, 0) similarly to ScintillatorResponse?
2) Why not have CherenkovResponse implement DetectorResponse?  Then you have access to sector based methods in DetectorResponse.  Certainly LTCC is sector based and HTCC could easily provide sector correlated information.

Cole

**Comment by josnewton** [comment]
Hello Cole,

The goal is to have all of the detector sub-types to inherit the
DetectorResponse class.  The Detector class in the common tools is a
little bit of a mess right now.  I hope to make the code more organized in
the coming days.  I just wanted to push some important additions to the
repository in the meantime.

-Joseph

**Comment by naharrison** [comment]
Your changes are failing the test that tries to reconstruct a subset of KPP events with 2 tracks. Before your changes there were 104 of these events reconstructed, now there are only 22.

**Comment by josnewton** [comment]
One of the changes I made related to neutral track identification.  If the
event Builder identifies a straight track in the calorimeter that bypassed
forward tracking, we assume it can be a photon.  I added a condition that
determines if any unmatched FTOF hit matches with the straight track in
the EC, we reject that track as a charged particle that missed tracking
but deposited energy in EC and FTOF.  I would be glad to look at these
files and compare these events directly with and without the change.

**Comment by forcar** [comment]
I do something similar to this except I define an FTOF hit with a cut just below the leading edge of the MIP energy distribution.  If you allow only 1-2 MeV FTOF hits these can come from backsplash of the shower in the EC, so you would be self-vetoing the photon shower.  On the other hand, if there is an FTOF MIP that was not caught by forward tracking we need to know why.  This is more of a DetectorResponse issue than EB, but thresholds have to be chosen carefully.

**Comment by forcar** [comment]
Joseph,

Below are the current parameterizations for photon and electron sampling fractions in ECAL (PCAL+EC).  The simulations include the effect of FTOF but do not include LTCC or other upstream detector elements.  The GEMC version was a month or so old (4a.1.0).  

Cole

**Comment by josnewton** [comment]
Thanks Cole.  Where are the parametrizations located?  I don't see them in
the e-mail or the github.

Best regards,
Joseph

**Comment by forcar** [comment]
Sorry, I should have used the git tool.  Below is a pdf showing the constants.

screen shot 2017-07-20 at 12 43 11 pm

**Comment by forcar** [comment]
Here is an updated version with normalized constants listed below the raw fit.  Also I extended the electron fit to the lowest energy bin.
screen shot 2017-07-20 at 2 27 06 pm

**Pull request merged**
