### PR TITLE
Bonusdev

### PR DESCRIPTION
**Pull request by dcpayette**

### CODE REVIEW

**Review by baltzell — APPROVED** [review]

**Comment by raffaelladevita** [comment]
What are the optimal RTPC service options for beam events, real data or MC? Those should be made default and the yamls updated.

**Comment by dcpayette** [comment]
The data.yaml includes the default options? I'm not sure what else you mean I'm sorry. Is there another yaml I need to change? We have always been using the data.yaml for cooking.

**Comment by raffaelladevita** [comment]
Can these options be made default in the code and be removed from the yaml? If these are the options that should be used anyway, it would be cleaner to set the service default configuration accordingly.

**Comment by dcpayette** [comment]
Without having them in the yaml at all it would limit our ability to study other things such as cosmics. I suppose I could commit a version without these settings in the yaml but I'd have to add them back if we wanted to do other studies. I have written some code in the engine to check if these exist, and if they do not to set them to the default values, and I believe those are correct. So worst case, I could just remove those from the yaml.

**Comment by baltzell** [comment]
I think the point is to have service configurations' defaults be the normal production operating mode, and avoid cluttering up the default YAML just to get what should have been the default.  Documenting what all the available service options are doesn't belong in the default YAML (otherwise it would already be huge, because there's a lot more than BONuS to think about).

But we could of course have a separate YAML for cosmics (actually it probably is already needed for CVT?).

Actually why do we have `data.yaml` and `reconstruction.yaml`?  And now it looks like one is for cosmics for BONuS(!) but you wouldn't know that without looking inside.

**Comment by dcpayette** [comment]
I made the updates to the yamls :)

**Review by raffaelladevita — APPROVED** [review]

**Pull request merged**
