### PR TITLE
implemented method gotoEvent in HipoDataSource

### PR DESCRIPTION
**Pull request by gavalian**
Now you can go to any event in HipoDataSource.

### CODE REVIEW

**Comment by forcar** [comment]
I assume this now makes it easier to read events in sequence?  Is the next step to provide this capability?

**Comment by gavalian** [comment]
I'm not sure what you mean by read events in sequence ? The readNext() was also reading them in sequence.

**Comment by forcar** [comment]
Instead of readNext() returning events 5 22 3 123 33 it would return 3 5 22 33 123 so I can timeline easily.

**Comment by gavalian** [comment]
I do not see the point to that, since you do not know where the events are for event # 3 5 22 33 123.
FX, requested to have this feature, I just put it back in. If it helps you, that's good too ;-)

**Pull request merged**
