### PR TITLE
Iss1001 denoise

### PR DESCRIPTION
**Pull request by raffaelladevita**
- implement yaml variable to control the reading of DC hits with order different from 0 (on by default)
- provide support for running in parallel two versions of DC clustering and AI-assisted-tracking inference for denoise validation

### CODE REVIEW

**Comment by raffaelladevita** [comment]
Can you check if the names of the additional banks, i.e. the prefix, look reasonable?

**Comment by gavalian** [comment]
If you changed the prediction bank to DN::tracks, would make sense to change the normal one to AI::tracks, no?

**Comment by raffaelladevita** [comment]
Yes, or I can make it dn::tracks or aidn::tracks, or AI::tracks, or AIDN::tracks...preferences?

**Comment by gavalian** [comment]
I personally prefer aidn::tracks

**Review by baltzell — APPROVED** [review]
If it works, ok for pass2, but seems to be getting complicated.  Could instead maybe be a single class that gets configured with the bank chaining and everyone else asks it for their i/o names.

**Comment by raffaelladevita** [comment]
The Bank class was supposed to be that but it can definitely be simplified. The attempt to implement a mechanism to generate the bank names based on a generic prefix is anyway kind of pointless since the bank json files need to be defined for the chosen prefix

**Pull request merged**
