### PR TITLE
Move build source/target to java 11

### PR DESCRIPTION
**Pull request by baltzell**

### CODE REVIEW

**Comment by gavalian** [comment]
This is what I'm using:

<maven.compiler.source>11</maven.compiler.source>
  <maven.compiler.target>11</maven.compiler.target>

Are these things same ?

**Comment by baltzell** [comment]
> This is what I'm using:
> 
> <maven.compiler.source>11</maven.compiler.source> <maven.compiler.target>11</maven.compiler.target>
> 
> Are these things same ?

Not sure.  Surely the 3.6.0 requirement is a bit different, but I don't know if release=11 propagates to both source and target.  We should find out.

**Comment by baltzell** [comment]
e.g. https://stackoverflow.com/questions/59049980/maven-compiler-release-as-an-replacement-for-source-and-target

**Comment by gavalian** [comment]
I think the post you sent suggested that we should use both,
 it may also be reason why the checks failed ?

**Comment by gavalian** [comment]
The file was not found. for some test.

**Comment by raffaelladevita** [comment]
It seems it was just a glitch (Clara startup failure). Retriggering the build fixed it

**Review by raffaelladevita — DISMISSED** [review]

**Review by gavalian — DISMISSED** [review]

**Review by raffaelladevita — APPROVED** [review]

**Pull request merged**
