### PR TITLE
Removed large field maps from history

### PR DESCRIPTION
**Pull request by naharrison**
Repository is less than half the original size

### CODE REVIEW

**Comment by drewkenjo** [comment]
it's hard to review given 3,842 files changed :) I understand all of them come from syncing your repo with upstream but it's hard to know for sure anyway. If you could delete your repo, fork/clone/change/submit PR again it would be much easier to review. Thanks!

**Comment by naharrison** [comment]
Just before submitting this pull request I did exactly what you suggested (delete fork, re-fork, clone, change, submit PR). The supposed 3,842 files changed seems to be a result of messing with the repo history, even though I only deleted 6 files. As far as I can tell this is our best (only?) option for getting rid of these large unnecessary files. The size improvement is 863M -> 425M.

**Comment by drewkenjo** [comment]
Hmm... that's strange. There is another way to get rid of them, using official git filter tool. It's extremely slow but given that we need it only once it doesn't matter. Let me check if it works.

**Comment by smancill** [comment]
Also, 400 MB is still too much, there are a lot of files that should not belong the repo:

    4eff28c71151  8.3MiB clasJlib/ced/v1.0/data/solenoid-srr.dat
    cb921b9ac312  8.3MiB common-tools/cnuphys/ced/data/clas12-fieldmap-solenoid.dat
    eb1a58562b35  9.4MiB coatjava/lib/clas/coat-libs-2.0-SNAPSHOT.jar
    3a87f391c022   11MiB coatjava/etc/data/magfield/clas12-fieldmap-torus.dat
    a89af8660b03   11MiB common-tools/cnuphys/coatjava/etc/data/magfield/clas12-fieldmap-torus.dat
    a2b87998bfba   13MiB common-tools/cnuphys/swimmer/data/clas12_small_torus.dat
    9304c02ce3da   13MiB common-tools/cnuphys/ced/data/HippoData/test.hipo
    94488a377124   17MiB coatjava/lib/clas/coat-libs-3.0-SNAPSHOT.jar
    4e221f2e2731   17MiB coatjava/lib/clas/coat-libs-3.0-SNAPSHOT.jar
    b1c9e7a9e99e   17MiB coatjava/lib/clas/coat-libs-3.0-SNAPSHOT.jar
    868f12cd6bda   17MiB coatjava/lib/clas/coat-libs-3.0-SNAPSHOT.jar
    47aa969490f0   17MiB lib/clas/coat-libs-3.0-SNAPSHOT.jar
    4a5aa885762c   19MiB common-tools/cnuphys/coatjava/lib/clas/coat-libs-3.0-SNAPSHOT.jar
    abc60527130a   19MiB common-tools/cnuphys/coatjava/lib/clas/coat-libs-3.0-SNAPSHOT.jar
    be3869adc6ca   19MiB coatjava/lib/clas/coat-libs-3.0-SNAPSHOT.jar
    d5536e89acec   24MiB common-tools/cnuphys/coatjava/lib/clas/coat-libs-4.0-SNAPSHOT.jar
    2085d8aa1f37   26MiB ced/data/smallAsciiMap.txt
    a2da3a647206   26MiB common-tools/cnuphys/swimmer/data/smallAsciiMap.txt
    6cc737c71fff   27MiB common-tools/cnuphys/coatjava/lib/clas/coat-libs-5.0-SNAPSHOT.jar
    f21c1b460fce   27MiB common-tools/cnuphys/coatjava/lib/clas/coat-libs-5.0-SNAPSHOT.jar
    aa4326d80bfc   27MiB common-tools/cnuphys/coatjava/lib/clas/coat-libs-5.0-SNAPSHOT.jar
    80d2bd6cc218   27MiB common-tools/cnuphys/coatjava/lib/clas/coat-libs-5.0-SNAPSHOT.jar
    037f28a35678   29MiB common-tools/cnuphys/coatjava/lib/clas/coat-libs-5.1-SNAPSHOT.jar
    3f95402b47ad   30MiB magfield/data/clas12SolenoidFieldMapOLD.dat
    4a346124ef04   30MiB magfield/data/clas12SolenoidFieldMap.dat.txt
    03877670efcf   71MiB ced/data/hipo/rec_dvcdgen28.hipo
    565984bfed3d   87MiB common-tools/cnuphys/ced/data/clas12-fieldmap-torus.dat

Those are almost 300 MB just for multiple versions of `coat-libs` jar.

**Comment by drewkenjo** [comment]
So the easiest solution would be to ask all collaborators to submit their changes from forks or branches. Then after deadline run BFG directly on development branch. Right?

**Comment by smancill** [comment]
Essentially, you need coordination. Make everybody aware that history has been totally rewritten, and their clones and forks are not synchronized with upstream anymore, and that they shouldn't merge but overwrite their copies (rewriting public history is a big no-no for this reason, it creates a problem for every cloner, but since the intention is to fix the repo size which is unnecessarily big, it seems a good trade off).

So, yes, ideally every PR should be merged before rewriting `development`, otherwise the PR should be rewritten too in top of the new head.

Then, everyone needs to hard reset their local `development` branch to the new head. You'll need to provide the command line instructions to do so. I just realized that most people are using forks, and recloning from the fork will not work, the fork will be still out of sync (unless they delete the fork, fork again and then clone).

I disagree with the way you are using forks, it creates issues when keeping up to date with upstream. The wiki doesn't even have instructions to add upstream nor to sync the fork with the latest changes. If people keep pushing to their `development` branch and opening pull requests, they will never be in sync with the latest changes. For example, and I am seeing this behavior already:

    A---B---E---F---G---K---L---M---N   develop
         \     /               /
          C---D-------H---I---J   user/develop

The first PR for `C` and `D` is merged in `F`, but then the user continues working on top of his fork's `development` branch, and creates a second PR for `H`, `I`, `J`, which is merged on `M`.

What's the problem? The users will never be up to date with the upstream `develop` branch, they keep working from where they forked (`B` in this example).

The right way to do it is to start `H` from `G` (i.e. make sure they are up to date with upstream before starting working on a new feature):

    A---B---E---F---G---K---L---M---N   develop
         \     /     \         /
          C---D       H---I---J   user/develop

Or never work on their local `develop` branch, and always create a new branch for every PR, after syncing with upstream first.

**Comment by drewkenjo** [comment]
well, I guess we assume that if someone forked the repo, he/she is able to add upstream and it's his/her responsibility to keep it up to date with main repo. We probably should add instruction to wiki though, you are right. Anyway, we need to coordinate with ppl to remove large files.

**Comment by forcar** [comment]
I’ve always followed Mauri’s instructions for the GEMC repo (below).  It always works, but I’ve been told rebase is the preferable procedure.

Cole

**Comment by smancill** [comment]
Just to be clear, by doing `git rm` you haven't changed the size of the repository. The removed files are still stored as blobs in the repository, and they will be there forever unless history is rewritten to make it so the files were never added.

By removing the files with `git rm` you have reduced only the size of the working tree. The **total size** of a clone is *working tree + .git directory*, and the size of *.git* is still the same.

If your goal is to reduce the size of the disk space occupied by a clone, then `git rm` will help a bit, as you pointed. But a new clone will still download all files, even if they are removed. You can further reduce the size of the clone by doing a shallow clone starting from a commit that doesn't contain the large files, at cost of not having the full history information.

**Pull request closed without merging**
