### PR TITLE
Time reconstruction development

### PR DESCRIPTION
**Pull request by forcar**
* Reads CCDB table /calibration/ec/timing
* Methods for setting and getting strip, peak and cluster time
* Peak time based on strip with largest energy
* Cluster time based on peak with largest energy
* Strip time corrected for readout distance using fixed effective velocity 16 cm/ns

### CODE REVIEW

**Comment by baltzell** [comment]
This only affects EC time reconstruction, right?

Can you run some EB tests on this first, e.g.:

```
cd validation/advanced-tests
./run-eb-tests.sh electronproton
```

**Comment by forcar** [comment]
Yes, there is no interaction at the moment between energy and time reconstruction aside from using the max energy to report the time.  

I’ve run it on my own pizero simulations.  Identical results before and after.   Below is TwoTrack results.

**Comment by baltzell** [comment]
The KPP TwoTrack test is pretty bogus at this point.  The EB tests, based on MC, are actually useful.

**Comment by forcar** [comment]
I ran the test you asked me to.  Was there another one you wanted?

**Comment by baltzell** [comment]
if the eb tests succeeded, then sounds good to me.

**Comment by forcar** [comment]
I tried the electrongamma EB test.

**Pull request merged**
